// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4vHpFlW4i_QMwjNtzts_m_UuUeiCuGj8',
    appId: '1:231505840801:web:55e8238b1a36ac9a69bee0',
    messagingSenderId: '231505840801',
    projectId: 'test-4904e',
    authDomain: 'test-4904e.firebaseapp.com',
    storageBucket: 'test-4904e.appspot.com',
    measurementId: 'G-FDSKNEMKZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2GzkFQHrwUFhZF1MUfYHGAodccUEPO84',
    appId: '1:231505840801:android:abfc397458a1248e69bee0',
    messagingSenderId: '231505840801',
    projectId: 'test-4904e',
    storageBucket: 'test-4904e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTO3kgFsW_8owesSXa6csximPj47H4f-E',
    appId: '1:231505840801:ios:b7fa9d864d6f1e6a69bee0',
    messagingSenderId: '231505840801',
    projectId: 'test-4904e',
    storageBucket: 'test-4904e.appspot.com',
    iosClientId: '231505840801-gt1h6snhtssvqso2ukks7g38kqok18pb.apps.googleusercontent.com',
    iosBundleId: 'z',
  );
}
